[package]
name = "cairn-md"
version = "0.1.0"
description = "A fast, local Markdown library for Windows"
authors = ["Cairn.md contributors"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/moosicalbovine/Cairn.md"

[lib]
name = "cairn_md_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
log = "=0.4.34"
serde = { version = "=1.0.229", features = ["derive"] }
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-log = "=2.9.1"
tauri-plugin-single-instance = "=2.4.4"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
